/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class br_usp_ime_bioinfogen_JBioinfoNativeTask */

#ifndef _Included_br_usp_ime_bioinfogen_JBioinfoNativeTask
#define _Included_br_usp_ime_bioinfogen_JBioinfoNativeTask
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     br_usp_ime_bioinfogen_JBioinfoNativeTask
 * Method:    execute
 * Signature: (Ljava/lang/String;Ljava/lang/String;IILbr/usp/ime/bioinfogen/GeneAnalisysProgressStatus;)I
 */
JNIEXPORT jint JNICALL
Java_br_usp_ime_bioinfogen_JBioinfoNativeTask_execute( JNIEnv *,
		jobject,
		jstring,
		jstring,
		jint,
		jint,
		jobject );

}
#ifdef __cplusplus

#endif
#endif
